{{- include "multi-site-app.validateSite" . -}}
{{- include "multi-site-app.validateRegion" . -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "multi-site-app.fullname" . }}
  labels:
    {{- include "multi-site-app.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range $host := (include "multi-site-app.hosts" . | fromYamlArray) }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "multi-site-app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          - path: /healthcheck
            pathType: Prefix
            backend:
              service:
                name: {{ include "multi-site-app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}