{{- include "multi-site-app.validateSite" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multi-site-app.fullname" . }}
  labels:
    {{- include "multi-site-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "multi-site-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "multi-site-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.site }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http